cilium/packer-ci-build

- README.md
- cilium.json
- http/preseed.cfg
- provision/install.sh
- provision/vagrant.sh
Copy of image building files from https://github.com/eloycoto/cilium_basebox.
This is done with permission from @eloycoto on GitHub.
> initial commit: copy base

- README.md
> README.md: update README

- provision/install.sh
- Added go-bindata
- Added gops
- Addedp linux tools
> Added dependencies

- cilium.json
- provision/envoy.sh
- provision/install.sh
- provision/pull-images.sh
- Updated to ubuntu 17.10
- Keep kernel 4.9 (Minimun supported)
- Added envoy dependencies
> Updated server to Ubuntu  17.10

- Jenkinsfile
- Makefile
- cilium-opensuse.json
- cilium-ubuntu.json
- Create a new Jenkinsfile
- If the branch is master, a new vagrantcloud image will be updated and
the build ID will be the version
- If the branch is not master. Only test if the image works.
> Added Jenkinsfile job for server

- Jenkinsfile
- cilium-opensuse.json
- cilium-ubuntu.json
- provision/env.bash
- provision/envoy.sh
- provision/golang.sh
- provision/pull-images.sh
- provision/registry.sh
- provision/ubuntu/install.sh
- provision/ubuntu/kernel.sh
- provision/vagrant.sh
Do not merge yet there's a PR I need to make in cilium/cilium first
> Envoy build improvements

- provision/golang.sh
> Replace jteeuwen/go-bindata with cilium/go-bindata

- provision/ubuntu/install.sh
> Adding default PATH to Vagrant user

- Jenkinsfile
- cilium-opensuse.json
- cilium-ubuntu.json
> Packer: Fix issues with virtualbox names conflicts

- cilium-opensuse.json
- cilium-ubuntu.json
> changed keep_input_artifact: false

- Jenkinsfile
- provision/envoy.sh
- provision/golang.sh
- provision/registry.sh
It turns out the build was never successful. I've fixed the patch and added an exit on error for all the bash scripts
> Fix envoy build

- provision/envoy.sh
- provision/pull-images.sh
If https://github.com/cilium/cilium/pull/2868 passes, we can merge this one.
> provision: switch python image tag to a slimmer one

- provision/env.bash
> provision: update bazel to 0.10.1

- provision/golang.sh
Related with https://github.com/cilium/cilium/commit/1218c6424015c05a13c22fa2feda3c5533c81801
> Added protoc-gen-validate as dependency

- cilium-opensuse.json
- cilium-ubuntu.json
- provision/swap.sh
- provision/ubuntu/install.sh
Needed by kubernetes >= 1.7
Related with: https://github.com/cilium/cilium/issues/3066
> Swap: Disable swap for kubernetes instalation.

- provision/envoy.sh
Temporary change to kick a build.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
> envoy.sh: Build branch 'envoy-integrate-logs'

- provision/envoy.sh
> Packer: Clone cilium from Master again

- Jenkinsfile
- provision/ubuntu/install.sh
Related with: https://github.com/cilium/cilium/issues/3399
> Enable cores in /tmp/ folder

- provision/ubuntu/install.sh
Related with: https://github.com/cilium/cilium/issues/3425
> Ubuntu: Disabled virtual address space randomization

- provision/ubuntu/install.sh
> Kernel: Fix kernel parameters to be persistent.

- provision/envoy.sh
Required by https://github.com/cilium/cilium/pull/3853
Signed-off-by: Romain Lenglet <romain@covalent.io>
> envoy.sh: Clone cilium from branch 'rebase-envoy'

- Jenkinsfile
- cilium-opensuse.json
- cilium-ubuntu.json
- provision/envoy.sh
Add a new option to be able to set a Jenkins Parameter with different
Cilium base branch.
> Packer: Use a env Variable ${CiliumBranch}.

- Jenkinsfile
- cilium-ubuntu.json
- provision/pull-images.sh
> Pull Cilium V1.0.0 docker images

- cilium-ubuntu.json
- provision/containerd.sh
- provision/env.bash
- provision/ubuntu/install.sh
> Added Containerd support in base images

- provision/golang.sh
- provision/pull-images.sh
- provision/ubuntu/install.sh
- Added new golang dependencies
- Pull correct istio images
- Added journald limits
Fix #55
> Build: Add new dependencies

- cilium-ubuntu.json
- provision/ubuntu/crio.sh
> add crio integration

- cilium-ubuntu.json
> Fix typo on cilium-ubuntu.json

- provision/golang.sh
> golang: Add ineffassign tool

- provision/pull-images.sh
> pull-images: add cilium-builder/runtime 2018-06-21

- provision/pull-images.sh
To speed up the test, use the specific labels for each container.
> Add specific labels on pull containers.

- cilium-ubuntu.json
- http/preseed.cfg
- provision/ubuntu/install.sh
> change Ubuntu image to 18.04 LTS

- cilium-opensuse.json
- cilium-ubuntu.json
> Fix path for aws cli

- provision/pull-images.sh
> provision: update cilium builder image to 2016-06-29

- provision/pull-images.sh
> provision: update cilium-builder to 2018-08-17

- provision/pull-images.sh
> provision: update cilium image tags

- provision/pull-images.sh
> provision: update cilium and microscope images

- provision/ubuntu/install.sh
> provision: add cfssl utility

- provision/pull-images.sh
> provision: update image tags

- provision/pull-images.sh
> Added 1.3 docker image

- provision/golang.sh
> Fix golang envtpl installation

- provision/pull-images.sh
Added docker images used in FQDN tests.
> Pull FQDN images.

- provision/pull-images.sh
> provision: pull istio images

- provision/ubuntu/containerd.sh
> Restart docker after install custom containerd

- provision/pull-images.sh
fixes https://github.com/cilium/cilium/issues/6056
fixes https://github.com/cilium/cilium/issues/5769
> Change bmemcached image to one from cilium org

- provision/env.bash
- provision/pull-images.sh
> Bump go to 1.12.0

- provision/ubuntu/kernel-next.sh
This will ease debugging of BPF-related issues.
> ubuntu-next: compile and install bpftool

- provision/pull-images.sh
> provision: add k8s.gcr.io/coredns:1.2.6

- provision/golang.sh
Was updated to envoyproxy org so the build is now failing.
> Protoc-gen-validate repository update.

- provision/pull-images.sh
> provision: download docker.io/cilium/istio_proxy_debug:1.0.0 image

- provision/pull-images.sh
> provision: update images for Istio v1.1.2

- provision/pull-images.sh
Signed-off by: Jarno Rajahalme <jarno@covalent.io>
> provision: update images for Istio v1.1.3

- provision/pull-images.sh
> cilium runtime: include latest iproute2 changes

- provision/env.bash
- provision/pull-images.sh
> provision: bump to go 1.12.5

- provision/pull-images.sh
> provision: updating builder and runtime images

- provision/golang.sh
can you take a look @jrajahalme 
> provision: remove unnecessary dependencies

- provision/pull-images.sh
Corresponds to PR https://github.com/cilium/cilium/pull/8237
> provision: Bump cilium-builder to 2019-06-06

- provision/pull-images.sh
- provision/vagrant.sh
> provision: update images cached in VM

- provision/pull-images.sh
> provision: update cilium-{builder,runtime} to 2019-09-26

- provision/env.bash
> provision: bump golang to 1.13.3

- provision/env.bash
- provision/pull-images.sh
- provision/ubuntu/kernel-next-bpftool.sh
> provision: update docker images

- provision/env.bash
- provision/pull-images.sh
> provision: update Go to 1.14.1

- provision/ubuntu/kernel.sh
Signed-off-by: Maciej Kwiek <maciej@isovalent.com>
> When adding 4.19 image, two packages were not installed

- provision/pull-images.sh
Update pre-pulled images to versions used by the CI with cilium-istioctl.
> Update pre-pulled images

- provision/pull-images.sh
Update to new tag for pre-pulling.
> cilium: prepull new runtime/builder images

- provision/ubuntu/install.sh
Fixes https://github.com/cilium/cilium/issues/11570
> Install protoc from github release instead of apt

- provision/golang.sh
Related to https://github.com/cilium/cilium/pull/11528
> Replace ineffassign by golangci-lint

- cilium-ubuntu-4.19.json
- cilium-ubuntu-next.json
- cilium-ubuntu.json
- provision/ubuntu/kernel-next-clean.sh
- provision/ubuntu/kernel-next.sh
> provision: Clean after installation

- cilium-ubuntu-4.19.json
- cilium-ubuntu-next.json
- cilium-ubuntu.json
- provision/pull-images.sh
- provision/ubuntu/netperf.sh
Used in CI (https://github.com/cilium/cilium/pull/12961).
> provision: prepull cilium/netperf image

- provision/pull-images.sh
This PR update GuestBook Docker images to match cilium/cilium#13003.
> provision: Update GuestBook Docker images

- provision/ubuntu/install.sh
LLVM 11.0.0 was just released.
> provision: Bump LLVM to 11.0.0

- provision/ubuntu/install.sh
- provision/ubuntu/kernel-next-bpftool.sh
> provision: Use same LLVM version as Docker images & log kernel HEAD commit

- provision/env.bash
- provision/pull-images.sh
> Bump Go version and add net-perf image

- provision/pull-images.sh
> provision: pre-pull alpine:3.13.0

- provision/env.bash
> provision: Bump Go version

- provision/pull-images.sh
Bump pre-pulled images for istio, alpine and cilium-{builder,runtime}
> Bump images

- provision/env.bash
- provision/pull-images.sh
Forgot to do this as part of #253
> provision: bump Go to 1.16

- provision/pull-images.sh
- Update log-gatherer:v1.1 (new vsn includes tcpdump)
- Add kube-wireguard:0.0.2.
> Update cached docker images list

- cilium-ubuntu-next.json
- provision/ubuntu/kernel-next.sh
> provision: Fix bpf-next build

- Jenkinsfile-5.4
- Makefile
- cilium-ubuntu-5.4.json
- provision/ubuntu/kernel.sh
The new build is not yet triggered by `test-me-please`, nor marked Required.
> Build Linux 5.4 VM image

- provision/pull-images.sh
Based on https://github.com/cilium/cilium/pull/16217/
> provision: Bump cilium-builder

- README.md
Signed-off-by: Tom Payne <tom@isovalent.com>
> docs: Add doc on updating images used in tests

- provision/ubuntu/install.sh
For >= 1.11 Cilium we gonna use the iproute2+libbpf for loading
programs.
Signed-off-by: Martynas Pumputis <m@lambda.lt>
> iproute2: Switch branch to libbpf-static-data

- provision/env.bash
> provision: Bump hubble cli to v0.9.0

- provision/ubuntu/kernel-next-download.sh
- provision/ubuntu/kernel-next.sh
> next: Fix perf build

- provision/pull-images.sh
The tests using these images have been removed from the Cilium repo.
> provision: drop unused test images

- provision/ubuntu/kernel-next.sh
This is sometimes useful for debugging.
> Enable iptables LOG target on net-next VM

- provision/env.bash
Ref. https://github.com/cilium/cilium/pull/23896#issuecomment-1442016906
> Update Go to 1.20.1

- provision/pull-images.sh
- provision/ubuntu/install.sh
Ref: https://github.com/cilium/cilium/pull/25338
Ref: https://github.com/cilium/image-tools/pull/215
> provision: Update LLVM, builder and runtime images

- provision/ubuntu/install.sh
As of Cilium 1.14, it no longer uses the ip command to load BPF programs into the kernel. This means we no longer need to maintain our patches on top of iproute2 and we no longer depend on a custom build in order for Cilium to run.
I've also removed bpftool here since I don't think we strictly depend on shipping bpftool from upstream master. @qmonnet
> provision: remove custom libbpf and iproute2 builds
