cilium/packer-ci-build

cilium.json, provision/install.sh
* change cert email
* remove Vagrant Cloud references
* Increase default number of CPUS
* Change naming scheme for resultant box
* Add compression_level and keep_input_artifact parameters / values
=> miscellaneous changes to port VM to Cilium repository

cilium.json, provision/install.sh, provision/kernel.sh
Hi @ianvernon,
Today I had a chat with @borkmann, and the problem with the new image was the LLVM version, sorted in the configuration. 
It is working now.
- Install 4.9 kernel 
- Updated grub to boot from 4.9 kernel
- Install 4.14 IP route
- Install 3.8.1 LLVM+Clang
Related to https://github.com/cilium/cilium/issues/2291
=> Ginkgo: Using kernel 4.9 LTS instead of 4.10.

http/opensuse.xml
lsb-release is needed to detect a distribution in Vagrant
provisioning scripts.
Ref #2497
=> opensuse: Add lsb-release package

Jenkinsfile
On build #1 the GIT_BRANCH is "master" instead of origin/master so it
didn't upload the build to vagrantcloud.
Log:
```
[lium_packer-ci-build_master-2HHAHSGBB76OCIXFXBDOFKDLILAPWMGN6BTSF3S2RV2RZIG6BB2Q] Running shell script
+ printenv
JENKINS_HOME=/var/jenkins_home
MAIL=/var/mail/root
USER=root
RUN_CHANGES_DISPLAY_URL=https://jenkins.cilium.io/job/cilium/job/packer-ci-build/job/master/1/display/redirect?page=changes
NODE_LABELS=ginkgo jenkins-node-0 nightly vagrant
HUDSON_URL=https://jenkins.cilium.io/
GIT_COMMIT=3d91319c38086ef652593a19a95c915fc3df5e8c
SHLVL=1
OLDPWD=/root
HOME=/root
BUILD_URL=https://jenkins.cilium.io/job/cilium/job/packer-ci-build/job/master/1/
HUDSON_COOKIE=d46b9225-cfcc-4e6f-b543-1fb83a356d5b
JENKINS_SERVER_COOKIE=durable-b799f4220dde52fc3a29c743d0491d98 …
```
=> Jenkinsfile: Fix issues with env.GIT_BRANCH

Jenkinsfile
This commit fixes a issue when the branch is master and JQ delete the
vagrantcloud section instead of keeping it.
=> Jenkinsfile: Fix issues with JQ on master

provision/ubuntu/install.sh
- Disabled systemd-resolved service
<https://github.com/cilium/cilium/issues/2750>
- Clean all ubuntu cache packages before upload to vagrantcloud
=> Disabled systemd-resolved service

provision/ubuntu/install.sh
Fix issues when try to install go-bindata:
```
[0;32m    virtualbox-iso: # cd .; git clone https://github.com/cilium/go-bindata /home/vagrant/go/src/github.com/cilium/go-bindata[0m
[0;32m    virtualbox-iso: Cloning into '/home/vagrant/go/src/github.com/cilium/go-bindata'...[0m
[0;32m    virtualbox-iso: fatal: unable to access 'https://github.com/cilium/go-bindata/': Could not resolve host: github.com[0m
[0;32m    virtualbox-iso: package github.com/cilium/go-bindata/...: exit status 128[0m
```
=> Ubuntu: Fix issues with the DNS

Jenkinsfile, cilium-opensuse.json, http/opensuse.xml, provision/opensuse/install.sh
Due to recent changes related to Envoy build, the following
dependencies needs to be installed:
- autoconf
- gettext-runtime
- gettext-tools
- ncurses5-devel
- libselinux-devel
- python3-Sphinx
- python3-sphinxcontrib-httpdomain
- python3-sphinxcontrib-openapi
- slang-devel
- util-linux
=> opensuse: Add missing packages

provision/envoy.sh
We need to add this patch temporarily so https://github.com/cilium/cilium/pull/2826 succeeds with its tests and we merge it into the repository
=> add patch to pre-build envoy with experimental_strict_action_env

Jenkinsfile, cilium-opensuse.json, cilium-ubuntu.json
Use Amazon S3 as datastore and publish the URL to VagrantCloud. 
=> Packer-CI: Send the images to Amazon S3 instead of vagrantcloud. 

Makefile, http/opensuse.xml, provision/envoy.sh, provision/opensuse/install.sh, provision/ubuntu/install.sh
This change installs bazel, recommonmark and sphinx-tabs from RPMs
in openSUSE and installs bazel from "upstream" scripts only in
Ubuntu.
=> opensuse: Install bazel, recommonmark and sphinx-tabs from RPMs

provision/env.bash
Upgrade Bazel to allow compiling the Istio Envoy filters (https://github.com/cilium/cilium/pull/3035).
Signed-off-by: Romain Lenglet <romain@covalent.io>
=> Upgrade Bazel to version 0.11.0

cilium-opensuse.json, http/opensuse.xml, provision/opensuse/etcd.sh, provision/opensuse/install.sh
opensuse: Use home:mrostecki:cilium as the only external repo
Go 1.9 is already shipped in openSUSE Tumbleweed.
Every other dependency which is needed for building cilium and
is not provided in the officcial Tumbleweed repo was moved
to home:mrostecki:cilium[1].
[1] https://build.opensuse.org/project/show/home:mrostecki:cilium
---
opensuse: Configure etcd service with 9732 and 9733 ports
=> openSUSE fixes

provision/pull-images.sh
Jenkins build are slow because need to donwload that image.
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/1812/testReport/k8s-1/9/K8sValidatedDemosTest_Tests_Star_Wars_Demo/
=> Add cilium/starwars image

provision/ubuntu/install.sh
This package allow use to run monitor with timestamps
```
vagrant@runtime1:~/go/src/github.com/cilium/cilium$ cilium monitor | ts '[%Y-%m-%d %H:%M:%S]'
[2018-04-03 17:34:26] Listening for events on 2 CPUs with 64x4096 of shared memory
[2018-04-03 17:34:26] Press Ctrl-C to quit
[2018-04-03 17:35:11] >> Endpoint regenerated: 29898 (reserved:health)
[2018-04-03 17:35:11] >> Endpoint regenerated: 38939 (container:id.httpd)
[2018-04-03 17:35:11] >> Endpoint regenerated: 173 (container:id.client)
[2018-04-03 17:35:11] >> Endpoint regenerated: 56326 (container:id.server)
```
Related to: https://github.com/cilium/cilium/issues/3233
=> Ubuntu: Installed moreutils package

provision/ubuntu/install.sh
Upgrading pip by itself to version 10.0 results in errors.[0]
[0] https://github.com/pypa/pip/issues/5240
=> ubuntu: Use pip from packages

provision/pull-images.sh
Had seen in the Jenkins that some images are not ready after timeout.
This make things a bit faster
=> Pull istio images in packer-ci-build

provision/env.bash, provision/envoy.sh, provision/ubuntu/install.sh
The cloned Cilium branch contains 'envoy/BAZEL_VERSION' file that
specified which version of Bazel to install. Use it so that we do not
need to keep updating the packer-ci-build repo every time Bazel
version is bumped.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
=> envoy: Use Bazel version of the cloned Cilium branch.

provision/ubuntu/install.sh
In common test environments, it is easy for LDS + NPDS configuration for
~10 endpoints to generate more than 1000 lines of log messages within a
second. To prevent losing logs in test environments, bump this ratelimit
to 10000.
=> ubuntu: Bump journald log ratelimit to 10000

provision/swap.sh
Found a PR triage that the CPU was used by Kswapd, so disable it just to
make sure that it's not user until is needed.
Doc:
https://askubuntu.com/questions/259739/kswapd0-is-taking-a-lot-of-cpu
```
38 root      20   0       0      0      0 S  18.8  0.0   3:17.73 kswapd0
```
=> Disable swappiness

provision/ubuntu/install.sh
Cf. the updated dependencies for building Istio 1.0.0 istio-proxy: https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers
Signed-off-by: Romain Lenglet <romain@covalent.io>
=> Install ninja-build on Ubuntu, now required to build Envoy

provision/golang.sh
At the moment the Golang dependencies are created by root user, this
means that the CI system will complain because `~/.cache/go-build`, this
commit install all golang programs as vagrant user.
Fix https://github.com/cilium/cilium/issues/5059
=> Install Golang dependencies as vagrant user.

provision/pull-images.sh
Pull in the cilium-init image from https://github.com/cilium/cilium/pull/5857 .
=> provision: Pull in new cilium-init container image

Jenkinsfile-next, Makefile, cilium-ubuntu-next.json, provision/ubuntu/install.sh, provision/ubuntu/kernel-next.sh
This is a new feature request.
This commit added support to create a new Ubuntu Virtualbox image to
upload it to `cilium/ubuntu-next` with the latest changes from the
kernel.
This commit consist in the following changes:
- Jenkinsfile-next to build ubuntu-next from other jobs.
- Makefile: Added distribution ubuntu-next
- kernel-next: To install a new kernel from net-next. ATM is applying a
patch that are not already merged in kernel.
- ubuntu/install: Add iproute from net-next (if specified) and the skip
vboxsf installation if is already present.
=> Ubuntu-next: Add the kernel net-next in ubuntu base image

cilium-ubuntu-next.json, provision/ubuntu/install.sh
When a new kernel is in place the vboxsf is only used when a shared
folder is in used, and that does not happens during the packer-ci-build.
With this change we validate that the kernel is greater than 1.17 where
vbox modules are already in there.
=> Test: Fix vbox additions on net-next kernel

cilium-ubuntu-next.json, provision/ubuntu/install.sh
VboxSF does not work with the current version of virtualbox installed.
With this change we make sure that the vbox filesystem can be mounted.
=> VBoxGuestAdditions: Install custom VBoxGuestAdditions on RC kernels

provision/ubuntu/kernel-next.sh
On net-next kernel the reboot was not in place, so when VboxAdditions is
installed is not correctly installed due is using the old kernel, so it
fails on vagrant import due no vboxsf module.
With this change, after install the net-next kernel a reboot is made to
start with the latest kernel.
=> Net-Next kernel fix shared folders

provision/ubuntu/kernel-next.sh
Net-next kernels support kTLS in order to test we need to add the CONFIG_TLS module support.
Signed-off-by: John Fastabend <john.fastabend@gmail.com>
=> cilium: packer ci builds include kTLS support

provision/pull-images.sh
Recent Cilium builds have been failing due to containers getting stuck in `ContainerCreating` state during the Kafka tests, specifically the Kafka broker. While this is because of network issues on the CI side (unrelated to Cilium), downloading this image should reduce the time the tests take, as well as insulate the CI against intermittent networking problems that are not in our control on the baremetal machines used in CI. 
Related Cilium issue: https://github.com/cilium/cilium/issues/6303
=> provision: pull Spotify Kafka proxy image

Makefile, provision/opensuse/install.sh, tools/download-opensuse-ovf.sh
The devel:kubic repository has no intention of being usable on stable
releases of openSUSE and packages needed for Cilium development are too
fresh to be included in stable releases. The rolling-release version
(Tumbleweed) needs to be used.
=> opensuse: Switch to Tumbleweed release

provision/ubuntu/install.sh
When running the latest version of the VM (127), yamllint is not in the path of
the vagrant user:
```
vagrant@runtime:~$ which yamllint
vagrant@runtime:~
```
This is because it is in `~/.local` directory, which the vagrant user cannot
access:
```
vagrant@runtime:~$ ls .local
ls: cannot open directory '.local': Permission denied
```
The permissions assigned to it reveal this:
```
vagrant@runtime:~$ ls -altr
total 60
...
drwx------ 4 root    root    4096 Jan 29 23:20 .local
...
```
This is fixed by changing the permissions on the directory to allow the vagrant
user to access it:
```
vagrant@runtime:~$ sudo chown -R "vagrant:vagrant" ~/.local
vagrant@runtime:~$ which yamllint
/home/vagrant/.local/bin/yamllint
```
Set the correct permissions in the install.sh script. Also fix the path for the …
=> provision: fix permissions for packages installed via pip3

cilium-opensuse.json, cilium-ubuntu-next.json, cilium-ubuntu.json
Fixes a small nit (creating this PR to trigger build of `ubuntu-next`).
=> ubuntu-next: Get rid of box_basename

provision/opensuse/install.sh, provision/pull-images.sh, provision/ubuntu/install.sh
Import new iproute2 changes:
* https://github.com/joestringer/iproute2/releases/tag/4.20.0-1ubuntu0bjn2
Also available from build services:
* PPA: https://launchpad.net/~joestringer/+archive/ubuntu/ppa
* OBS: https://build.opensuse.org/package/show/home:joestringer:branches:security:netfilter/iproute2-cilium
These are necessary for https://github.com/cilium/cilium/issues/6618.
The corresponding cilium repo PR is https://github.com/cilium/cilium/pull/7114 .
=> provision: Pull in custom iproute2 changes

cilium-ubuntu-next.json, provision/ubuntu/kernel-next.sh, provision/ubuntu/vboxsf-next.sh
This PR:
- Fixes (again) vboxsf on 18.04.2.
- Changes the order of installation of the vboxsf module installation to prevent from being overwritten by the guest additions.
- Enables parallelism for compiling the kernel.
=> ubuntu-next: Fix vboxsf on 18.04.2

cilium-ubuntu-next.json, provision/ubuntu/kernel-next.sh
It is being set in `provision/ubuntu/install.sh`.
Fixes: 6c6477ca3 ("provision: Pull in custom iproute2 changes")
=> ubuntu-next: Do not set IPROUTE_BRANCH

provision/ubuntu/vboxsf-next.sh
Otherwise, vboxsf complains when mounting:
```
vboxsf: Old binary mount data not supported, remove obsolete mount.vboxsf and/or update your VBoxService.
```
Signed-off-by: Martynas Pumputis <m@lambda.lt>
=> ubuntu-next: remove obsolete mount.vboxsf binary

Jenkinsfile
OpenSUSE Tumbleweed is currently broken, leading to master build errors like this:
https://jenkins.cilium.io/job/Vagrant-Master-Boxes-Packer-Build/135/execution/node/26/log/
```
15:58:16     virtualbox-ovf: Resolving package dependencies...
15:58:16     virtualbox-ovf: 5 Problems:
15:58:16     virtualbox-ovf: Problem: iproute2-cilium-4.20-187.1.x86_64 requires libm.so.6(GLIBC_2.29)(64bit), but this requirement cannot be provided
15:58:16     virtualbox-ovf: Problem: cri-o-1.13.0-2.8.x86_64 requires libostree-1.so.1()(64bit), but this requirement cannot be provided
15:58:16     virtualbox-ovf: Problem: docker-18.09.1_ce-1.1.x86_64 requires iproute2 >= 3.5, but this requirement cannot be provided
15:58:16     virtualbox-ovf: Problem: python3-docker-compose-1.23.2-2.2.noarch requires …
```
=> Temporarily disable opensuse build

provision/pull-images.sh, provision/ubuntu/install.sh
The version we pointed to only had the patches as files inside the repo,
not applied to the actual codebase. Fix it by pointing to a branch that
actually has the patches applied.
=> Fix iproute2 image pull

provision/ubuntu/kernel.sh
Due some CI test are hitting issues that has been fixed in kernel 4.9
updated to do not hit this issue.
=> Kernel: Update to a newer version of 4.9 kernel

provision/env.bash, provision/pull-images.sh
As well bump image tags that are built with go 1.12.1
=> bump to go 1.12.1

cilium-ubuntu-next.json, net-next-patches/bpf-gso.patch, net-next-patches/bpf-map-alloc.patch, provision/ubuntu/kernel-next.sh
To make Cilium integration tests to work on `ubuntu-next`, we need to manually apply the following patches (both accepted) until they get merged to the bpf-next tree:
- bpf-map-alloc.patch: Fix BPF map memory allocations: https://lore.kernel.org/bpf/efeee51e-bb64-333d-7091-5c768c13e5e9@iogearbox.net/.
- bpf-gso.patch: Fix NAT46: https://lore.kernel.org/bpf/20190313191250.158955-6-sashal@kernel.org/.
Once they have been merged, I will create a new PR to remove the patches.
=> net-next: Apply BPF-related patches

provision/pull-images.sh
To cut VM image build time and CI run time. 
Based on grepping `cilium/test`.
=> Update list of pre-pulled Docker images

provision/opensuse/install.sh
Tumbleweed accepted the static data POC changes:
https://build.opensuse.org/request/show/682651
Switch to the upstream iproute2 now that we don't need to rely on my
personal OpenSUSE repository with the changes.
=> OpenSUSE: Switch to standard cilium package

provision/pull-images.sh
Cache the image \[1\] in a VM image, as it used by the Cilium CI. https://github.com/cilium/cilium/issues/7740 could have been avoided if we had cached the image.
\[1\]: https://github.com/cilium/cilium-etcd-operator/blob/v2.0.6/pkg/defaults/const.go#L31
Signed-off-by: Martynas Pumputis <m@lambda.lt>
=> Cache etcd-operator:v0.9.4 image

cilium-ubuntu-next.json, cilium-ubuntu.json, provision/opensuse/install.sh, provision/ubuntu/kernel-next-bpftool.sh, provision/ubuntu/kernel-next.sh
bpftool is going to be required for Cilium runtime for BPF feature
probes.
=> Add bpftool

provision/golang.sh
sonobuoy is a diagnostic tool for checking the state of Kubernetes
cluster with conformance tests. Cilium is going to have Jenkins jobs
which run that tool.
Ref: cilium/cilium#8161
=> Add sonobuoy

provision/env.bash, provision/golang.sh, provision/opensuse/install.sh, provision/ubuntu/install.sh
This is the follow up change which installs sonobuoy from release
tarball (on Ubuntu) or package (on openSUSE) instead of using `go get`.
Fixes: ecab44e403a6 ("Add sonobuoy")
=> Install sonobuoy from release tarball or package

cilium-ubuntu-next.json, cilium-ubuntu.json
With Packer v1.4.1, the trailing slash in mirror URL was causing a failure when downloading ISO files which lead to the invalid checksum:
```
==> virtualbox-iso: Retrieving ISO
==> virtualbox-iso: Trying
http://cdimage.ubuntu.com//ubuntu/releases/18.04/release/ubuntu-18.04.2-server-amd64.iso
==> virtualbox-iso: Trying
http://cdimage.ubuntu.com//ubuntu/releases/18.04/release/ubuntu-18.04.2-server-amd64.iso?checksum=sha256%3Aa2cb36dc010d98ad9253ea5ad5a07fd6b409e3412c48f1860536970b073c98f5
. 4.51 KiB / ?
[--------------------------------------------------------=----------------------------------------------------------------------------------------]
46.15% 0s
==> virtualbox-iso: Checksum did not match, removing
/home/brb/github/packer-ci-build/packer_cache/0e12e96c14de872d5159c48d34aa560e0ceb …
```
=> Remove trailing slash in ubuntu URL mirrors

provision/ubuntu/kernel-next.sh
This should prevent from the `/var/lib/docker/overlay2/ID/merged: device
or resource busy` error which was observed when testing the host-lb: https://github.com/cilium/cilium/pull/8100.
The workaround was suggested by https://github.com/moby/moby/issues/34672#issuecomment-347994879.
=> ubuntu-next: Disable overlayfs index

cilium-ubuntu-next.json, net-next-patches/disable-lowerdir-is-in-use-check.patch, provision/ubuntu/kernel-next.sh
https://github.com/torvalds/linux/commit/146d62e5a5867fbf84490d82455718bfb10fe824 introduced a check for an overlayfs lowerdir being in-use by upperdir/workdir which makes Docker 18.09 to fail when pushing "k8s1:5000/cilium/cilium-dev" on the latest RC kernel.
The symptom is docker-push failing with `/var/lib/docker/overlay2/$DIR/merged: device or resource busy` and dmesg having the `overlayfs: lowerdir is in-use as upperdir/workdir` log entry.
This PR patches the kernel to disable the check until Docker has fixed the underlying issue. The included patch is NOT meant to be upstreamed.
Also, we re-enable the overlayfs index since Docker disables it by default.
=> next: Disable overlayfs check for lowedir being in-use by upperdir/workdir

provision/pull-images.sh
We don't run microscope in the CI anymore, so remove the image.
=> provision: remove microscope image

provision/pull-images.sh
The image is used by tests introduced in https://github.com/cilium/cilium/pull/9399.
=> Pull cilium/json-mock image

provision/env.bash, provision/pull-images.sh
Also update the base images that contain golang 1.13.4
=> update golang to 1.13.4

provision/ubuntu/vboxsf-next.sh
Currently, when using the latest ubuntu-next (v37), `mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant` fails (no error message is returned).
Update the vboxsf kernel module which might fix the issue.
=> ubuntu-next: Update vboxsf

provision/ubuntu/kernel-next-bpftool.sh
To include the patch \[1\]. Once it has been included into bpf-next.git, we will switch back the tree.
\[1\]: https://git.kernel.org/pub/scm/linux/kernel/git/davem/net.git/commit/?id=cc52d9140aa920d8d61c7f6de3fff5fea6692ea9
=> Temporarily switch to bpf.git tree

provision/pull-images.sh
It's going to be used by tests introduced by https://github.com/cilium/cilium/pull/9728.
=> Pull cilium/echoserver image

provision/pull-images.sh
The images are going to be used by the `"Tests MetalLB"` test introduced in https://github.com/cilium/cilium/pull/9694.
=> Pull metallb (v0.8.2) images

provision/env.bash, provision/pull-images.sh
Based loosely upon the images being pulled here:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/16222/execution/node/107/log/?consoleFull
Plus grepping the latest master tree for the cilium images.
=> Update golang and image prepull versions

provision/pull-images.sh, provision/ubuntu/kernel-next-bpftool.sh
We need to rebuild ubuntu-next to contain the newest version of
iproute2. However, since Cilium currently fails to pass CI on the
5.5-rc's, we pin the net-next tag to v5.4 so we can have a new Vagrant
box without updating the kernel.
Additionally bumps the prepull images.
=> ubuntu-next: Pin net-next kernel version to v5.4

provision/ubuntu/kernel-next-bpftool.sh
The 5.5 kernel has been released \[1\]. Update ubuntu-next to use the kernel, so that we can test whether EPERM issue still persists \[2\].
\[1\]: https://lwn.net/Articles/810578/
\[2\]: https://github.com/cilium/cilium/pull/9657#issuecomment-577628794
=> ubuntu-next: Bump kernel to v5.5

provision/ubuntu/kernel.sh
This should resolve BPF_MAP_GET_NEXT_KEY getting stuck issue mentioned
in \[1\].
\[1\]: https://github.com/cilium/cilium/pull/9972#issuecomment-580351617
/cc @Rolinh
=> ubuntu-dev: Bump kernel version to 4.9.212

provision/pull-images.sh
Prefetch the cilium/echoserver-udp image used by the UDP service
connectivity tests introduced in cilium/cilium#9997.
=> provision: Prefetch cilium/echoserver-udp image

provision/ubuntu/containerd.sh
Should save ~50MB in the resulting VM image.
=> containerd: remove cri-containerd tarball after unpacking

provision/ubuntu/install.sh
After cilium/cilium#10204 is merged, this is no longer needed.
=> ubuntu: don't install libc6-dev

provision/pull-images.sh
The use of the image was introduced in https://github.com/cilium/cilium/pull/10119/.
=> Cache cilium/log-gatherer:v1.0 image

provision/ubuntu/kernel-next-bpftool.sh
Cilium fork of the Linux kernel contains necessary enhancements for
bpftool which are not avalavle upstream yet.
Ref: cilium/cilium#10048
=> Use Cilium fork of the kernel to build bpftool

cilium-ubuntu-next.json, provision/ubuntu/kernel-next-tools.sh, provision/ubuntu/kernel-next.sh
Install perf into ubuntu-next machine which can be used to troubleshoot packet drops on CI machines (`perf record -g -a -e skb:kfree_skb && perf script`).
=> net-next: Install perf

cilium-ubuntu-4.19.json, cilium-ubuntu-next.json, cilium-ubuntu.json, provision/ubuntu/install.sh
For details see: https://github.com/cilium/cilium/pull/10542/
=> packer-ci: install newer llvm/clang from repo

provision/ubuntu/install.sh
The images are regularly missing documentation dependencies because they are currently hardcoded in the VM provisioning scripts. This commit changes the script to use the latest list of documentation dependencies from the cilium repository.
CI tests currently need #195. I tested the VM image provisioning locally in the meantime.
Fixes #78.
/cc @mrostecki
=> Use doc. dependencies from cilium repo.

provision/ubuntu/install.sh
=> add conntrack for kubeadm >= 1.18

provision/ubuntu/kernel-next-bpftool.sh
Switch to the bpf tree to pick up the fix 8e368dc72e86 ("bpf: Fix use of
sk->sk_reuseport from sk_assign"). We can switch back to bpf-next after
it's merged there.
=> ubuntu: Switch to 'bpf' tree to pick up fixes

provision/pull-images.sh
This will pull in Go 1.14.2 via cilium/cilium#10912 and the build llvm
changes from cilium/cilium#10956
=> provision: pull latest cilium base images

provision/pull-images.sh, provision/ubuntu/install.sh
This adds the hubble binary to the VM (for use in Runtime tests) and pre-pulls the image used in K8s tests.
=> Add Hubble

provision/ubuntu/kernel-next-bpftool.sh
In order to pull in most recent changes:
- https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=0ee52c0f6c67e187ff1906f6048af7c96df320c7
- https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=1b66d253610c7f8f257103808a9460223a087469
- https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=f15ed0185de7d471e907783739dffbe397a93142
- https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=05ee19c18c2bb3dea69e29219017367c4a77e65a
- https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=566fc3f5d1c641b510ec487cf274a047f8a1e849
=> packer, next: move kernel tree from bpf to bpf-next

provision/pull-images.sh
- cilium-{builder,runtime} images were updated in cilium/cilium#11542
- istio was updated in ciliu/cilium#11530
- etcd:v3.4.7 is needed for test/k8sT/manifests/etcd-deployment.yaml as
of cilium/cilium#11544
=> provision: pull latest cilium, istio and etcd images

provision/ubuntu/install.sh
Specify only the targets we need from the llvm build, namely `clang` and
`llc`. This reduces the amount of objects to build by ~300 and thus
also reduces build time a bit.
Same as cilium/cilium#10956
=> provision/ubuntu: only build clang and llc targets

http/preseed.cfg, provision/env.bash, provision/pull-images.sh
* provision: pull latest cilium images
* provision: update Go to 1.14.3
* don't install kernel headers and source in preseed
Please see individual commit for details
=> pull latest cilium images, bump Go version, don't preseed kernel headers/sources

provision/pull-images.sh
With cilium/cilium#11728 all alpine-curl and busybox image versions are
unified, so only alpine-curl:0.1.8 and busybox:1.31.1 need to be
pre-pulled
docker.io/prom/prometheus and docker.io/prom/statsd-exporter are no
longer used after cilium/cilium#10851 and cilium/cilium#7712, so they
don't need to be pre-pulled.
quay.io/coreos/etcd-operator:v0.9.4 is used nowhere in CI, drop it.
=> provision: clean up list of pre-pulled images

provision/ubuntu/install.sh
Given this is used for dev VMs, it's useful to have x86 around as well
since it's used e.g. in the BPF unit tests that the CI runs. So running
it locally, x86 backend would be needed, too.
Note that this does not affect the cilium-runtime image which does not
have the x86 backend (and will never have it again).
=> llvm: re-enable x86 next to bpf backend

provision/ubuntu/install.sh
This is the newest Hubble CLI release.
Note: The pre-pulled 0.5 images will likely be removed in a separate PR once we have updated Cilium CI to not pull these images anymore.
=> provision: Bump Hubble CLI to 0.6.0

provision/ubuntu/install.sh
CI runs occasionally fail with errors similar to:
```
Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource
temporarily unavailable)
Unable to acquire the dpkg frontend lock
(/var/lib/dpkg/lock-frontend), is another process using it?
```
This lock is typically held by `dpkg` or `apt` when they check for or proceed to updates. The two main suspects are usually:
- An aborted run of `dpkg` or `apt`, that would not have released the lock   on exit, or
- Automatic updates running in the background, for example with the `unattended-upgrades` package.
The logs did not raise any previous apt failure. Automatic updates may well be responsible for the lock being held. We do not want them running on test machines anyway, so let's disable `unattended-updates` altogether.
=> provision/ubuntu: disable unattended-upgrades

provision/pull-images.sh, provision/ubuntu/install.sh
Building the vagrant images currently fails because
`setup.py install` for `sphinx-rtd-theme-cilium` needs `npm` and `nodejs`.
Install these in the provision script.
Also pull the latest Cilium images and drop the unused
docker.io/cilium/cilium:v1.6 image.
=> provision: install nodejs/npm and pull latest Cilium images

provision/env.bash, provision/pull-images.sh, provision/ubuntu/install.sh
In addition, downloads the binary artifacts from GitHub releases instead
of building it manually.
=> provision: Bump Hubble to v0.6.1

provision/pull-images.sh, provision/ubuntu/kernel-next.sh
Also, while we are here, cache the `cilium/echoserver:1.10.1` image used by the Cilium CI.
=> Enable building of wireguard module on net-next

provision/ubuntu/install.sh
We need these header files to compile the BPF unit tests inside the development VMs.
Related: https://github.com/cilium/cilium/issues/11255
Fixes: #218
=> provision: Install headers required for Clang

provision/env.bash, provision/pull-images.sh, provision/ubuntu/install.sh
This change hasn't been released in any of the branches yet,
but is required for CI coverage so we pin a specific hash.
Signed-off-by: Glib Smaga <code@gsmaga.com>
=> provision: Update hubble to recent API

provision/pull-images.sh
The image (https://github.com/cilium/dummylb) replaces the MetalLB used in the Cilium's integration tests. See https://github.com/cilium/cilium/pull/12852 for more details.
=> Cache docker.io/cilium/dummylb:0.0.1

provision/ubuntu/kernel-next.sh
Working on and testing pahole, llvm, and other tooling requires BTF. For
example running bpf-next sefltests requires it to run all the tests
correctly. Lets add it to the list of kernel config options we enable
so we can run selftests and other tools from inside the bpf-next kernel
image.
Signed-off-by: John Fastabend <john.fastabend@gmail.com>
=> packer-ci-builds: Enable BTF debug info in kernel

provision/ubuntu/install.sh
This reverts commit 15d6adbcb3d93aece8fe643245f5ec56e3e202ae.
We can't update to LLVM 11.0.0 just yet because we are hitting verifier issues for that version (and complexity issues for the LLVM trunk). I'm reverting this commit to unblock other image updates.
=> Revert "provision: Bump LLVM to 11.0.0"

provision/ubuntu/kernel-next.sh
Enable DEBUG_INFO so that DEBUG_INFO_BTF will actually work.
Fixes: 97a0ca7e21e98 ("packer-ci-builds: Enable BTF debug info in kernel")
Signed-off-by: John Fastabend <john.fastabend@gmail.com>
=> packer-ci-builds: For BTF debug info to work we need base DEBUG_INFO

provision/pull-images.sh
Pull request https://github.com/cilium/cilium/pull/14093 removed all references to :latest in our tests, preferring stable image tags. This pull request updates the list of pre-pulled images accordingly.
=> provision: Update Docker images

provision/env.bash, provision/pull-images.sh, provision/ubuntu/install.sh
Pull the latest istio images and install latest hubble v0.7.1 from binary artifacts
The hash cilium/hubble@186fa10 pinned in commit 570378f4f58b
has been included since hubble v0.7.0:
$ git tag --contains=186fa10
v0.7.0
v0.7.1
=> Update istio and hubble

provision/env.bash, provision/pull-images.sh
- Bump Go to 1.15.7
- Update `k8s.gcr.io/coredns` images to what is actually used in CI.
- Drop `docker.io/cc-grpc-demo` as it is not used in CI, only in GSG docs
- Pre-pull `golang` image to slightly speed up local Cilium image build
- Update `cilium-{envoy,builder,runtime}` to latest versions
=> Update Go and pre-pulled images

provision/env.bash, provision/pull-images.sh, provision/ubuntu/install.sh
This pulls in the lastest master version of the Hubble CLI. This is
needed to test the API changes to embedded Hubble in Cilium master,
specifcially cilium/cilium#14785
Ref: https://github.com/cilium/cilium/pull/14923
The pulled docker image remains at the released 0.7.1 version, as this
is what the Cilium master Dockerfile pulls in.
=> provision: Bump Hubble to latest master

provision/pull-images.sh
We no longer build Cilium on Jenkins from the VMs so there is not point
on downloading such images locally.
=> remove quay.io/cilium/cilium-{runtime,builder} images

cilium-ubuntu-4.19.json, provision/ubuntu/kernel.sh
It seems, the 4.19 kernel version we currently use (4.19.57) is no
longer available from https://kernel.ubuntu.com/~kernel-ppa/mainline
leading to the 4.19 image being built without a 4.19 kernel and using
the default 4.15 kernel. This breaks CI tests relying on 4.19+ features
(such as BPF NodePort). Thus bump to the latest 4.19 micro release
4.19.177.
=> Bump kernel 4.19 package

provision/ubuntu/kernel.sh
Like the 4.19 kernel package (see #256), the 4.9 kernel version
(4.9.212) is no longer available from https://kernel.ubuntu.com/~kernel-ppa/mainline
leading to the 4.9 image being built without a 4.9 kernel and using
the default 4.15 kernel. This breaks 4.9 specific CI tests  Thus bump to
the latest 4.9 patch release 4.9.258.
Also make sure we catch any errors in the kernel provisioning script, so
it should be easier to detect these cases during image build.
=> Bump kernel 4.9 package

cilium-ubuntu-4.19.json, cilium-ubuntu-next.json, cilium-ubuntu.json, provision/fix-home-ownership.sh, provision/vagrant.sh
Before this PR, many files and directories are owned by root, meaning
that the vagrant user could not create or update files.
This PR adds a final step to fix the ownership.
Signed-off-by: Tom Payne <tom@isovalent.com>
=> provision: Fix ownership of /home/vagrant

provision/pull-images.sh
It was bumped in the CI by
https://github.com/cilium/cilium/commit/37291016a4a5e2e204c9d9027afbb2c5c639407a.
Signed-off-by: Martynas Pumputis <m@lambda.lt>
=> Bump kube-wireguard version

provision/pull-images.sh
It is used in test/k8sT/manifests/frr.yaml.tmpl in Cilium
=> provision: Pre-pull docker.io/frrouting/frr:v7.5.1

provision/ubuntu/install.sh
It will be used to dump wireguard status (incl. peers) in bugtool.
=> Install wireguard tools

cilium-ubuntu-5.4.json
Because https://github.com/cilium/packer-ci-build/pull/263 was not rebased to include https://github.com/cilium/packer-ci-build/pull/262 it broke ownerships for `.ssh` in the new 5.4 box.
Fixes: https://github.com/cilium/packer-ci-build/pull/263
=> Fix .ssh ownership for 5.4 box

provision/pull-images.sh
https://github.com/cilium/packer-ci-build/pull/254 removes the `cilium-{runtime,builder}` images from the list of pre-pulled images. The `cilium-builder` image is however still used by [K8sVerifier](https://github.com/cilium/cilium/blob/v1.10.0-rc0/test/k8sT/manifests/test-verifier.yaml) in Cilium's CI tests.
This pull request adds `cilium-builder` back, with the new tag from https://github.com/cilium/cilium/pull/15790.
=> provision: Add cilium-builder back to pre-pulled images

provision/ubuntu/install.sh
Install Cilium's CLI when building the images, to provide an easy way to configure Cilium on its cluster, retrieve its status, or launch connectivity checks for example.
No specific use case at the moment, other than to provide the CLI out-of-the-box on the dev and test VMs.
=> provision: install Cilium CLI

provision/ubuntu/kernel.sh
The packages for 4.9.258 are not available for download anymore, so bump to 4.9.270, which should stay longer (as it's a multiple of 5). See b956b07 ("Bump kernel 4.19 package") for details.
With that change, all three kernels for which we use packages are now on multiples of 5.
=> provision: Bump 4.9 kernel packages

provision/ubuntu/install.sh
This reverts commit 430530bfee5a9738decfd85912491101357c4ce4.
We can't simply install the cilium CLI in the VMs for Runtime tests and development because, in those VMs, Cilium runs as a service. That means `cilium` already executes the CLI for the Cilium agent in those VMs.
=> Revert "provision: install Cilium CLI"

provision/ubuntu/install.sh
The `ipset` binary is required in the VMs because of https://github.com/cilium/cilium/pull/16603 when Cilium is running as a service (e.g., for development VMs and for Runtime tests).
=> provision: Install `ipset` binary

bpf-next-patches/0001-cpumask-Omit-terminating-null-byte-in-cpumap_print_-.patch, cilium-ubuntu-next.json, provision/ubuntu/kernel-next.sh
Add a patch [1] to the bpf-next kernel build which fixes a regression
which causes kubelet to error out on startup.
See [2] and following comments for details.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c86a2d9058c5a4a05d20ef89e699b7a6b2c89da6
[2] https://github.com/cilium/cilium/pull/17394#issuecomment-920902042
Suggested-by: Daniel Borkmann <daniel@iogearbox.net>
Signed-off-by: Tobias Klauser <tobias@cilium.io>
=> provision: add patch to fix cpumask regression breaking kubelet

bpf-next-patches/0001-Revert-bpf-Support-8-byte-scalar-spill-and-refill.patch, provision/env.bash, provision/ubuntu/kernel-next.sh
Daniel confirmed that the upstream patch [`354e8f1970f8 ("bpf: Support <8-byte scalar spill and refill")`](https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/kernel/bpf/verifier.c?h=for-next&id=354e8f1970f821d4952458f77b1ab6c3eb24d530) breaks loading of Cilium's `bpf_overlay.o` when `tunnel=vxlan`, see https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/304. Revert that patch for now until a proper fix is upstreamed.
While at it also update Go to 1.17.2 and Hubble CLI to 0.8.2.
=> Revert bpf-next commit breaking bpf loading of Cilium's bpf_overlay.o

cilium-ubuntu-next.json
The net-next image provisioning currently has the following warning message:
k8s1+: Checking for guest additions in VM...
k8s1+: The guest additions on this VM do not match the installed version of
k8s1+: VirtualBox! In most cases this is fine, but in rare cases it can
k8s1+: prevent things such as shared folders from working properly. If you see
k8s1+: shared folder errors, please make sure the guest additions within the
k8s1+: virtual machine match the version of VirtualBox you have installed on
k8s1+: your host and reload your VM.
k8s1+:
k8s1+: Guest Additions Version: 5.2.20
k8s1+: VirtualBox Version: 6.0
=> provision: Fix warning for guest additions

provision/ubuntu/install.sh
During the creation of the VM images, we compile LLVM from sources into static binaries. This needs to be kept in sync with the LLVM build for the Docker images. That build takes almost 30 minutes, half the build time of VM images except for net-next.
Instead, we can simply retrieve the binaries included in the Docker images and copy them to the VM. We already install Docker in the VMs, so we just need to run `docker cp`.
=> provision: Retrieve LLVM binaries from images

cilium-ubuntu-4.19.json, cilium-ubuntu-5.4.json, cilium-ubuntu-next.json, cilium-ubuntu.json, provision/ubuntu/install.sh, provision/ubuntu/kernel-next.sh
In https://github.com/cilium/packer-ci-build/pull/289, the VM images were significantly changed to upgrade Ubuntu, but also to specialize the net-next kernel's config (https://github.com/cilium/packer-ci-build/commit/d1841cb1162ae91efbae11d5b9709ed880fdcc9c). The corresponding pull request in cilium/cilium,  https://github.com/cilium/cilium/pull/17761, uncovered many issues which are fixed in the present pull request.
The resulting net-next VM image was tested locally by replacing the usual Vagrant VM image with the newly-built image and running the full set of `K8s` and `Runtime` tests. A couple tests (e.g., `K8sIstio`) still fail, but they seem unrelated to kernel support, so maybe some other issue with running locally. In any case, we can always iterate fix further fixes later.
See …
=> Fix VM images to pass Cilium's tests

provision/pull-images.sh
Update cilium-builder image to sync with
https://github.com/cilium/cilium/pull/17980.
Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>
=> provision: update cilium-builder image

cilium-ubuntu-4.19.json, cilium-ubuntu-5.4.json, cilium-ubuntu.json
Currently, the aws CLI used to upload the boxes on master builds are
invoked with `--debug` leading to the logs being flooded with lots of
AWS CLI debug log messages, see [1] for a recent example. This makes it
hard to analyze the logs for earlier interesting log messages, so
disable these debug logs.
[1] https://jenkins.cilium.io/view/Packer%20builds/job/Vagrant-Master-Boxes-Packer-Build-5.4/19/console
=> Disable debug mode on AWS S3 upload

provision/pull-images.sh
https://github.com/cilium/cilium/pull/18018 updated the tests in
cilium/cilium to consistenly use CoreDNS v1.8.3. Thus we no longer need
to pre-pull any other CoreDNS image versions.
=> provision: only pull CoreDNS v1.8.3 image

provision/ubuntu/kernel-next-bpftool.sh
To dump JIted programs, bpftool needs the `libbfd-dev` dependency. That package is installed via another package at some time during provisioning, but after the bpftool compilation. As a result, the bpftool binary in the VMs is currently unable to dump the JITed programs.
=> provision: Enable bpftool to dump JITed programs

cilium-ubuntu-next.json, kernel-patches/bpf-Fix-incorrect-state-pruning-for-8B-spill-fill.patch, provision/ubuntu/kernel-next.sh
The latest bpf-next sources include a bug introduced by [354e8f1970f8](https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf.git/commit/?id=354e8f1970f8) ("bpf: Support <8-byte scalar spill and refill") that causes incorrect dead code elimination on Cilium's datapath. That in turn causes CT state entries to be missing and reply packets to be dropped in CI tests.
This regression is fixed in [345e004d0233](https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf.git/commit/?id=345e004d023343d38088fdfea39688aa11e06ccf) ("bpf: Fix incorrect state pruning for <8B spill/fill") includes in this commit. We need to include it as a separate patch until it lands in bpf-next (currently in bpf).
=> bpf-next: Fix incorrect dead code elimination

provision/ubuntu/kernel-next.sh
Istio uses the `owner` iptables module and the `CONNMARK` target. These kernel configs are therefore necessary to run the K8sIstio test in Cilium CI.
This change was tested locally using the K8sIstio test from cilium/cilium.
=> provision: Update net-next kernel config for Istio

provision/pull-images.sh
- update test-verifier image to latest version used in CI
- add docker.io/cilium/graceful-termination-test-apps:1.0.0
=> provision: updated pre-pulled images

cilium-ubuntu-4.19.json
This reverts commit 29fcc296cac7bc42f4b366a6054d169e2fbaee68.
From that commit:
A new complexity issue was reported in cilium/cilium with default
configuration on kernel 4.19.208+. We can update our 4.19 image to
try and catch it if it affects Cilium's master.
Spoiler: it does. And since we don't have a workaround, we need to revert this kernel update for now. The complexity issue is tracked at https://github.com/cilium/cilium/issues/17647.
=> Revert "Update to kernel 4.19.210"

cilium-ubuntu-4.19.json, cilium-ubuntu-5.4.json, cilium-ubuntu-next.json, cilium-ubuntu.json, provision/ubuntu/install.sh, provision/ubuntu/kernel-next-download.sh
There is now a GitHub mirror available for bpftool. Let's use it to download and compile the tool, instead of downloading the entire kernel repository for all images.
This should not save any disk space or boot time on the VM themselves, but should accelerate the builds (except for ubuntu-next, where building from the kernel sources that were already downloaded or from the mirror makes little difference).
=> Use bpftool mirror instead of building from bpf-next repository

provision/ubuntu/install.sh
In the past, we added to the ubuntu/install.sh script some commands to disable the unattended-upgrades service when provisioning the VM. However, it seems that something is still re-enabling the unattended-upgrades, which sometimes hinders the launch of the VM because the apt lock is held by that process.
As an additional step to prevent the launch of unattended-upgrades, let's remove the package from the system.
=> provision: Remove package unattended-upgrades from Ubuntu

provision/ubuntu/kernel-next-download.sh
This reverts commit 4446884838718675da4ec69718fd52966c6a446c.
The upstream commit was pulled in bpf-next so we don't need to cherry-pick it anymore.
=> Revert "next: Fix perf build"

provision/ubuntu/install.sh
Commit 18b7307 ("provision: Remove package unattended-upgrades from Ubuntu") attempted to prevent apt-get from holding the update lock as that can cause the VM provisioning to fail in CI.
It seems it wasn't enough however as the issue is still happening. This pull request attempts an additional fix by not even checking if updates exist.
Related: https://github.com/cilium/packer-ci-build/issues/315.
=> provision: Don't check for updates with apt-get

provision/ubuntu/install.sh
Disable apt-daily-upgrade and apt-daily jobs to avoid APT holding the
locks and occasionally making the VMs fail to provision correctly
Fixes: #315
=> provision: disable apt-daily and apt-daily-upgrade services

provision/env.bash, provision/golang.sh
Matching the versions currently used on Cilium `master` branch.
=> provision: update Go to 1.18.1, golangci-lint to 1.45.2

provision/ubuntu/kernel-next.sh
This module is used for container runtimes that are not docker.
=> provision: add OVERLAY_FS module

provision/ubuntu/kernel-next.sh
This reverts pull request https://github.com/cilium/packer-ci-build/pull/327.
This kernel config is not needed after all.
=> Revert "provision: add OVERLAY_FS module"

provision/ubuntu/install.sh
Add the cilium repo to the list of git safe directory exceptions for the
root user in order to allow installing Cilium.
This fixes the:
fatal: unsafe repository ('/home/vagrant/go/src/github.com/cilium/cilium' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /home/vagrant/go/src/github.com/cilium/cilium
error raised by git when running as root
=> provision: add git exception for cilium repo for root user

provision/ubuntu/containerd.sh, provision/ubuntu/kernel-next.sh
This reverts commit 89f73739a9f8c171cc9bf80fb98875357cdfe62a.
This kernel config is needed after all.
=> Revert "Revert "provision: add OVERLAY_FS module""

provision/ubuntu/install.sh
Apparently when installing our custom fork of iproute2, the compiled
executable is installed in `/usr/sbin` but the old iproute2 it is
supposed to overwrite still exists in `/usr/bin`. This is no issues as
long as `/usr/sbin` is positioned earlier in the `PATH` env var. But
this is not always the case.
This commit removes the old iproute2 executable so the new executable is
always used.
Signed-off-by: Dylan Reimerink <dylan.reimerink@isovalent.com>
=> Removed old iproute2 executable

provision/ubuntu/kernel-next.sh
This will allow tests to utilize SCTP. These options are consistent with
Ubuntu's default options.
Signed-off-by: Harsh Modi <harshmodi@google.com>
=> ubuntu: Enable SCTP support for the net-next kernel.

provision/pull-images.sh
These images were only used by the memcache runtime tests which were
removed in cilium/cilium#20132. Thus, these no longer need to be
pre-pulled.
=> provision: drop memcache test images

provision/pull-images.sh
Every time we run the end-to-end tests, we pull those images because they are not cached in the VMs. Let's fix that.
=> provision: Prepull all Cilium images

provision/golang.sh
Privileged tests will benefit from printing in a table to make it easier
for developres to parse the output and understand how long tests take.
Add mfridman/tparse to help do this in the VM environment.
=> Add mfridman/tparse for better Go test output

provision/pull-images.sh
This image is used for SCTP tests.
Signed-off-by: Harsh Modi <harshmodi@google.com>
=> provision: Pre-pull the networkstatic/iperf3 image.

provision/ubuntu/install.sh
Running Hubble in the VMs fails with the following error message, because Relay is not deployed and there is nothing to listen to at the default address:
failed to connect to 'localhost:4245': connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:4245: connect: connection refused"`
We can have Hubble working on its own by exporting the `HUBBLE_SERVER` environment variable and making it point to the Hubble socket.
Let's use /etc/environment so that the variable is exported for all users, and Hubble remains accessible when working as root.
=> provision: Export HUBBLE_SERVER socket

provision/ubuntu/kernel.sh
We have been hitting a kernel bug on 4.9 for the verifier tests. An underflow on the memlock rlimit counter, caused by the reallocation of BPF programs not updating the charged values, makes the counter go under zero and convert into a huge value, [blocking all further loads of BPF objects][0].
This has been [fixed in kernel 4.10][1], and was backported at last in 4.9.326.
Note: We need to update again soon towards a patch version which is a multiple of 5 (4.9.330), given that other releases are not kept for a long time, see commit b956b0726059 ("Bump kernel 4.19 package").
[0]: https://github.com/cilium/cilium/issues/20288
[1]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=5ccb071e97fbd9ffe623a0d3977cc6d013bee93c
=> provision: Bump 4.9 kernel packages (4.9.326, to fix a kernel bug)

provision/ubuntu/kernel-next.sh
When I first build the minimal kernel config, I think I only tested it by running the end-to-end tests which for, net-next CI job, run with KPR=strict. Thus, kube-proxy was probably not, or barely, tested.
This commits adds a few kernel configs that are currently causing errors for kube-proxy in the development VM.
Reported-by: Maxim Mikityanskiy <maxim@isovalent.com>
Signed-off-by: Paul Chaignon <paul@cilium.io>
=> Enable kernel configs for kube-proxy

cilium-ubuntu-5.4.json
We can't update 4.19 because we have a complexity issue there. 4.9 is already using the latest version (considering we have to use a rounded version or they get recycled quickly).
=> Update patch version used for 5.4 kernel

provision/pull-images.sh
Use registry.k8s.io to pull the coredns image, see https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/ for details.
The gb-frontend and gb-redis-follower images are no longer used by cilium/cilium CI, so they can be dropped.
=> provision: use registry.k8s.io

provision/golang.sh
This is to include https://github.com/mfridman/tparse/pull/95 for https://github.com/cilium/cilium/pull/25703.
=> Update tparse to unreleased 0.10.3
